name: Deploy to Plesk

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Notify Plesk Webhook
        run: |
          curl -X POST "https://prod1.aisle8.net:8443/modules/git/public/web-hook.php?uuid=e9500f0a-879d-9282-c4aa-f3cdfa6334cf"
